[2025-04-15T07:10:44.861+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T07:10:44.902+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_basics.dbt_test scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-15T07:10:44.916+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_basics.dbt_test scheduled__2025-04-14T00:00:00+00:00 [queued]>
[2025-04-15T07:10:44.916+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-15T07:10:44.932+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_test> on 2025-04-14 00:00:00+00:00
[2025-04-15T07:10:44.949+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_basics', 'dbt_test', 'scheduled__2025-04-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/basic/dbt_basics.py', '--cfg-path', '/tmp/tmpe1e6pi2h']
[2025-04-15T07:10:44.951+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask dbt_test
[2025-04-15T07:10:44.958+0000] {logging_mixin.py:190} WARNING - /root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=446) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-15T07:10:44.959+0000] {standard_task_runner.py:72} INFO - Started process 448 to run task
[2025-04-15T07:10:45.055+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_basics.dbt_test scheduled__2025-04-14T00:00:00+00:00 [running]> on host 9a8ef20dd1da
[2025-04-15T07:10:45.203+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_basics' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T00:00:00+00:00'
[2025-04-15T07:10:45.204+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-15T07:10:45.231+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-15T07:10:45.232+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --project-dir /app/airflow/dbt_lewagon']
[2025-04-15T07:10:45.246+0000] {subprocess.py:99} INFO - Output:
[2025-04-15T07:10:48.508+0000] {subprocess.py:106} INFO - [0m07:10:48  Running with dbt=1.9.1
[2025-04-15T07:10:49.955+0000] {subprocess.py:106} INFO - [0m07:10:49  Registered adapter: bigquery=1.9.0
[2025-04-15T07:10:50.887+0000] {subprocess.py:106} INFO - [0m07:10:50  Found 2 models, 4 data tests, 489 macros
[2025-04-15T07:10:50.890+0000] {subprocess.py:106} INFO - [0m07:10:50
[2025-04-15T07:10:50.890+0000] {subprocess.py:106} INFO - [0m07:10:50  Concurrency: 1 threads (target='dev')
[2025-04-15T07:10:50.891+0000] {subprocess.py:106} INFO - [0m07:10:50
[2025-04-15T07:10:51.468+0000] {subprocess.py:106} INFO - [0m07:10:51  1 of 4 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2025-04-15T07:10:53.539+0000] {subprocess.py:106} INFO - [0m07:10:53  1 of 4 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 2.07s]
[2025-04-15T07:10:53.541+0000] {subprocess.py:106} INFO - [0m07:10:53  2 of 4 START test not_null_my_second_dbt_model_id .............................. [RUN]
[2025-04-15T07:10:55.889+0000] {subprocess.py:106} INFO - [0m07:10:55  2 of 4 PASS not_null_my_second_dbt_model_id .................................... [[32mPASS[0m in 2.35s]
[2025-04-15T07:10:55.892+0000] {subprocess.py:106} INFO - [0m07:10:55  3 of 4 START test unique_my_first_dbt_model_id ................................. [RUN]
[2025-04-15T07:10:57.962+0000] {subprocess.py:106} INFO - [0m07:10:57  3 of 4 PASS unique_my_first_dbt_model_id ....................................... [[32mPASS[0m in 2.07s]
[2025-04-15T07:10:57.964+0000] {subprocess.py:106} INFO - [0m07:10:57  4 of 4 START test unique_my_second_dbt_model_id ................................ [RUN]
[2025-04-15T07:11:00.204+0000] {subprocess.py:106} INFO - [0m07:11:00  4 of 4 PASS unique_my_second_dbt_model_id ...................................... [[32mPASS[0m in 2.24s]
[2025-04-15T07:11:00.257+0000] {subprocess.py:106} INFO - [0m07:11:00
[2025-04-15T07:11:00.258+0000] {subprocess.py:106} INFO - [0m07:11:00  Finished running 4 data tests in 0 hours 0 minutes and 9.37 seconds (9.37s).
[2025-04-15T07:11:00.319+0000] {subprocess.py:106} INFO - [0m07:11:00
[2025-04-15T07:11:00.320+0000] {subprocess.py:106} INFO - [0m07:11:00  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-04-15T07:11:00.320+0000] {subprocess.py:106} INFO - [0m07:11:00
[2025-04-15T07:11:00.321+0000] {subprocess.py:106} INFO - [0m07:11:00  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2025-04-15T07:11:00.322+0000] {subprocess.py:106} INFO - [0m07:11:00    Got 1 result, configured to fail if != 0
[2025-04-15T07:11:00.322+0000] {subprocess.py:106} INFO - [0m07:11:00
[2025-04-15T07:11:00.323+0000] {subprocess.py:106} INFO - [0m07:11:00    compiled code at target/compiled/dbt_lewagon/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2025-04-15T07:11:00.323+0000] {subprocess.py:106} INFO - [0m07:11:00
[2025-04-15T07:11:00.324+0000] {subprocess.py:106} INFO - [0m07:11:00  Done. PASS=3 WARN=0 ERROR=1 SKIP=0 TOTAL=4
[2025-04-15T07:11:01.462+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-15T07:11:01.481+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T07:11:01.486+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_basics, task_id=dbt_test, run_id=scheduled__2025-04-14T00:00:00+00:00, execution_date=20250414T000000, start_date=20250415T071044, end_date=20250415T071101
[2025-04-15T07:11:01.500+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-15T07:11:01.501+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 448)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T07:11:01.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-15T07:11:01.536+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T07:11:01.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
