[2025-04-15T07:26:53.284+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T07:26:53.318+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_advanced.test.dbt_lewagon.not_null_my_first_dbt_model_id manual__2025-04-15T07:26:34.586994+00:00 [queued]>
[2025-04-15T07:26:53.328+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_advanced.test.dbt_lewagon.not_null_my_first_dbt_model_id manual__2025-04-15T07:26:34.586994+00:00 [queued]>
[2025-04-15T07:26:53.328+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-04-15T07:26:53.350+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): test.dbt_lewagon.not_null_my_first_dbt_model_id> on 2025-04-15 07:26:34.586994+00:00
[2025-04-15T07:26:53.371+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_advanced', 'test.dbt_lewagon.not_null_my_first_dbt_model_id', 'manual__2025-04-15T07:26:34.586994+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/advanced/dbt_advanced.py', '--cfg-path', '/tmp/tmp7a2_xews']
[2025-04-15T07:26:53.376+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask test.dbt_lewagon.not_null_my_first_dbt_model_id
[2025-04-15T07:26:53.374+0000] {logging_mixin.py:190} WARNING - /root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1221) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-15T07:26:53.378+0000] {standard_task_runner.py:72} INFO - Started process 1224 to run task
[2025-04-15T07:26:53.483+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_advanced.test.dbt_lewagon.not_null_my_first_dbt_model_id manual__2025-04-15T07:26:34.586994+00:00 [running]> on host 9a8ef20dd1da
[2025-04-15T07:26:53.636+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_advanced' AIRFLOW_CTX_TASK_ID='test.dbt_lewagon.not_null_my_first_dbt_model_id' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T07:26:34.586994+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T07:26:34.586994+00:00'
[2025-04-15T07:26:53.637+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-15T07:26:53.661+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-15T07:26:53.662+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test --models not_null_my_first_dbt_model_id --project-dir /app/airflow/dbt_lewagon']
[2025-04-15T07:26:53.677+0000] {subprocess.py:99} INFO - Output:
[2025-04-15T07:26:57.487+0000] {subprocess.py:106} INFO - [0m07:26:57  Running with dbt=1.9.1
[2025-04-15T07:27:00.064+0000] {subprocess.py:106} INFO - [0m07:27:00  Registered adapter: bigquery=1.9.0
[2025-04-15T07:27:00.995+0000] {subprocess.py:106} INFO - [0m07:27:00  Found 2 models, 4 data tests, 489 macros
[2025-04-15T07:27:00.998+0000] {subprocess.py:106} INFO - [0m07:27:00
[2025-04-15T07:27:01.000+0000] {subprocess.py:106} INFO - [0m07:27:00  Concurrency: 1 threads (target='dev')
[2025-04-15T07:27:01.001+0000] {subprocess.py:106} INFO - [0m07:27:00
[2025-04-15T07:27:01.645+0000] {subprocess.py:106} INFO - [0m07:27:01  1 of 1 START test not_null_my_first_dbt_model_id ............................... [RUN]
[2025-04-15T07:27:03.990+0000] {subprocess.py:106} INFO - [0m07:27:03  1 of 1 FAIL 1 not_null_my_first_dbt_model_id ................................... [[31mFAIL 1[0m in 2.34s]
[2025-04-15T07:27:04.044+0000] {subprocess.py:106} INFO - [0m07:27:04
[2025-04-15T07:27:04.045+0000] {subprocess.py:106} INFO - [0m07:27:04  Finished running 1 test in 0 hours 0 minutes and 3.04 seconds (3.04s).
[2025-04-15T07:27:04.209+0000] {subprocess.py:106} INFO - [0m07:27:04
[2025-04-15T07:27:04.209+0000] {subprocess.py:106} INFO - [0m07:27:04  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-04-15T07:27:04.210+0000] {subprocess.py:106} INFO - [0m07:27:04
[2025-04-15T07:27:04.211+0000] {subprocess.py:106} INFO - [0m07:27:04  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2025-04-15T07:27:04.211+0000] {subprocess.py:106} INFO - [0m07:27:04    Got 1 result, configured to fail if != 0
[2025-04-15T07:27:04.212+0000] {subprocess.py:106} INFO - [0m07:27:04
[2025-04-15T07:27:04.213+0000] {subprocess.py:106} INFO - [0m07:27:04    compiled code at target/compiled/dbt_lewagon/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2025-04-15T07:27:04.213+0000] {subprocess.py:106} INFO - [0m07:27:04
[2025-04-15T07:27:04.214+0000] {subprocess.py:106} INFO - [0m07:27:04  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-04-15T07:27:05.433+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-15T07:27:05.454+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T07:27:05.459+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_advanced, task_id=test.dbt_lewagon.not_null_my_first_dbt_model_id, run_id=manual__2025-04-15T07:26:34.586994+00:00, execution_date=20250415T072634, start_date=20250415T072653, end_date=20250415T072705
[2025-04-15T07:27:05.474+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-15T07:27:05.476+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task test.dbt_lewagon.not_null_my_first_dbt_model_id (Bash command failed. The command returned a non-zero exit code 1.; 1224)
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/02-dbt-in-airflow-BsnH11MF-py3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-15T07:27:05.511+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-15T07:27:05.557+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T07:27:05.559+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
